base/urls.py
from django.urls import path

from . import views as index_views

urlpatterns = [
    path('a/', index_views.base, name='index'),
]

books/urls.py
from django.urls import path
from django.conf.urls import url

from . import views as books_views
from . import dashboard
from . import journal
from . import income_statement
from . import input
from . import books_list
from . import books_edit
from . import export

urlpatterns = [
    # input
    path('input/product/new/', input.register_product, name='register_product'),
    path('input/income/new/', input.register_income, name='register_income'),
    path('input/expense/new/', input.register_expense, name='register_expense'),

    # books list
    path('books/product/list/', books_list.list_of_product, name='list_of_product'),
    path('books/expense/list/', books_list.list_of_expense, name='list_of_expense'),
    path('books/income/list/', books_list.list_of_income, name='list_of_income'),

    # books edit
    path(r'books/product/edit/<int:pk>/', books_edit.edit_product, name='edit_product'),
    path(r'books/product/delete/<int:pk>/', books_edit.delete_product, name='delete_product'),

    path(r'books/expense/edit/<int:pk>/', books_edit.edit_expense, name='edit_expense'),
    path(r'books/expense/delete/<int:pk>/', books_edit.delete_expense, name='delete_expense'),

    path(r'books/income/edit/<int:pk>/', books_edit.edit_income, name='edit_income'),
    path(r'books/income/delete/<int:pk>/', books_edit.delete_income, name='delete_income'),

    # journal and profit loss
    path('books/journal/', journal.journal, name='journal'),
    path('books/profit-loss/', income_statement.profit_loss, name='profit_loss'),

    # dashboards
    path('dashboard/', dashboard.user_dashboard, name='user_dashboard'),
    path('admin/dashboard/', dashboard.admin_dashboard, name='admin_dashboard'),

    # export
    url('books/journal/export/csv/', export.export_journal_to_csv, name='journal_to_csv'),
    url('books/ledger/pdf/', export.export_profit_loss_to_pdf, name='profit_loss_to_pdf'),

    # misc
    path('ajax/expense-dropdown/', books_views.expense_dropdown_ajax, name='dropdown_ajax'),
    path('ajax/income-autofill/', books_views.income_form_autofill_ajax, name='income_form_autofill'),
]

vislane/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('books.urls')),

    path('', include('base.urls')),
]

books/models.py
from django.db import models
from django.conf import settings

from user.models import Industry

from datetime import date

# Create your models here.

# Dependent dropdown model
class ExpenseCategory(models.Model):
    category = models.CharField(max_length=55)

    def __str__(self):
        return self.category

class SubCategory(models.Model):
    category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)
    sub_category = models.CharField(max_length=55)

    def __str__(self):
        return self.sub_category
# End of dependent dropdown model

class Product(models.Model):
    goods = 'Barang'
    services = 'Jasa'
    PRODUCT_TYPES = [
        (goods, 'Barang'),
        (services, 'Jasa'),
    ]

    username = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, null=True
    )

    product_name = models.CharField(max_length=155, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    types = models.CharField(
        choices=PRODUCT_TYPES,
        max_length=50,
        default=goods,
        null=False, blank=False,
    )

    def __str__(self):
        return self.product_name
    
class Journal(models.Model):
    # REMINDER !!!
    # This models kind of unsecure because it allows user to pass a NULL values for some fields if they rewrote the front-end code from developer console, because some of the authentication system only limited to the front-end side.
    # Possibly need a better solution for the future to merge two models into one table inside the template (not at the DB side of thing), instead of combining all of it into one models like this
    # Or maybe use additional validation in views.py to make sure the required submitted fields does not empty

    DB = 'Debit'
    CR = 'Kredit'
    BOOK_TYPE = [
        (DB, 'Debit'),
        (CR, 'Kredit'),
    ]

    date_added = models.DateField(
        default=date.today
    )
    username = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    industry = models.ForeignKey(Industry, on_delete=models.PROTECT)

    # Income Specific
    product_name = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=False)
    additional_price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True, default=0)

    # Expense Specific
    item_name = models.CharField(max_length=155, blank=False)
    category = models.ForeignKey(
        ExpenseCategory, on_delete=models.PROTECT,
        blank=False, null=True
        )
    sub_category = models.ForeignKey(
        SubCategory, on_delete=models.PROTECT,
        blank=False, null=True
        )

    # General
    quantity = models.IntegerField(null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    book_category = models.CharField(
        max_length=25,
        choices=BOOK_TYPE,
        )
    notes = models.TextField(max_length=255, null=True, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.book_category
    

books/forms.py
from django import forms
from django.conf import settings
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField

from datetime import date
from .models import Journal, ExpenseCategory, SubCategory, Product

class IncomeForm(forms.ModelForm):
    date_added = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'class':'form-control form-control-sm',
                'type':'date'
                }
        ),
        initial = date.today,
    )
    quantity = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class':'form-control form-control-sm',}
        ),
        initial = 0,
    )

    price = forms.DecimalField(
        widget=forms.NumberInput(
            attrs={
                'class':'form-control form-control-sm',
                'placeholder': 'Harga...',
                }
        )
    )
    additional_price = forms.DecimalField(
        widget=forms.NumberInput(
            attrs={
                'class':'form-control form-control-sm',
                'placeholder': 'Harga Tambahan...',
                }
        ),
        required=False,
        initial=0
    )
    notes = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class':'form-control form-control-sm',
                'placeholder': 'Notes...',
                }
        ),
        required=False,
    )
    class Meta:
        model = Journal
        fields = [
            'date_added', 'product_name', 'quantity', 'price', 
            'additional_price', 'notes'
        ]
    
    # This to filter the product name based on user
    # You need to rewrite a function inside ModelForm to be able to fetch requested user in the ModelForm, couse apparently you can't do it normally like in views.py
    # The requirement for this was to call request.user when calling the form in views.py, in this case IncomeForm(request.user, ...)
    def __init__(self, user, *args, **kwargs):
        super(IncomeForm, self).__init__(*args, **kwargs)
        self.fields['product_name'] = forms.ModelChoiceField(
            queryset=Product.objects.filter(username=user).order_by('product_name'),
            widget=forms.Select(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder': 'Nama Produk...',
                    }
            ),
            required=True,
        )

class ExpenseForm(forms.ModelForm):
    date_added = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'class':'form-control form-control-sm',
                'type':'date',
                }
        ),
        initial=date.today
    )
    
    item_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control form-control-sm',
                'placeholder': 'Nama Barang...',
                }
        )
    )
    category = forms.ModelChoiceField(
        queryset=ExpenseCategory.objects.all().order_by('category'),
        widget=forms.Select(
            attrs={
                'class':'form-control form-control-sm',
                'placeholder': 'Kategori...',
                }
        )
    )
    sub_category = forms.ModelChoiceField(
        queryset=SubCategory.objects.none(),
        widget=forms.Select(
            attrs={
                'class':'form-control form-control-sm',
                'placeholder': 'Kategori Tambahan...',
                }
        )
    )
    quantity = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class':'form-control form-control-sm',}
        ),
        initial = 0,
    )
    price = forms.DecimalField(
        widget=forms.NumberInput(
            attrs={
                'class':'form-control form-control-sm',
                'placeholder': 'Harga...',
                }
        )
    )
    notes = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class':'form-control form-control-sm',
                'placeholder': 'Catatan Tambahan...'
                }
        ),
        required=False,
    )
    class Meta:
        model = Journal
        fields = [
            'date_added', 'item_name', 'category', 'sub_category', 
            'quantity', 'price', 'notes'
        ]

    # This is to get sub_category data based on its foreign key
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sub_category'].queryset = SubCategory.objects.none()

        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields['sub_category'].queryset = SubCategory.objects.filter(
                    category_id=category_id
                ).order_by('-sub_category')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['sub_category'].queryset = SubCategory.objects.filter(
                category_id=self.instance.category_id
            )

class ProductForm(forms.ModelForm):
    goods = 'Barang'
    services = 'Jasa'
    PRODUCT_TYPES = [
        (goods, 'Barang'),
        (services, 'Jasa'),
    ]

    product_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder': 'Nama Produk...',
                }
        )
    )
    price = forms.DecimalField(
        widget=forms.NumberInput(
            attrs={
                'class':'form-control',
                'placeholder': 'Harga...',
                }
        )
    )

    types = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class':'form-control'}
        ),
        choices=PRODUCT_TYPES,
    )

    class Meta:
        model = Product
        fields = {
            'product_name', 'price', 'types'
        }

books/views.py
from django.shortcuts import render

from .models import Product, SubCategory

# Ajax for categories and sub categories dependent dropdown
def expense_dropdown_ajax(request):
    categories = request.GET.get('category')
    sub_categories = SubCategory.objects.filter(
        category=categories
    ).order_by('-sub_category')

    content = {
        'sub_categories': sub_categories,
    }
    return render(request, 'books/category_ajax.html', content)
# End of ajax categories and sub categories

# Ajax for autofill income form
def income_form_autofill_ajax(request):
    product_name = request.GET.get('product_name')
    price = Product.objects.filter(
        id=product_name
    )

    content = {
        'product_price': price,
    }
    return render(request, 'books/income_form_autofill.html', content)
# end of ajax autofill income form

books/templates/books/category_ajax.html
<option value="">------------</option>
{% for i in sub_categories %}
    <option value="{{i.pk}}">
        {{i.sub_category}}
    </option>
{% endfor %}

books/templates/books/income_form_autofill.html
{% for i in product_price %}
    {{i.price}}
{% endfor %}

books/templates/books/register_expense.html
{% extends 'base/base_test.html' %}

{% block title %}
Add Expenses
{% endblock title %}

{% block css %}
<link href="/../../static/books/books.css" rel="stylesheet">
<link href="/../../static/books/register_expense.css" rel="stylesheet">
{% endblock css%}

{% block register_expense %}

{% endblock register_expense%}

{% block content %}
<div class="page-content">
    <div class="w-100 h-100">
        <div>
            {% if messages %}
                {% for msg in messages %}
                    {% if msg.tags %}
                        <div class="col-8 msg-{{msg.tags}}-container">
                            <p class="msg-{{msg.tags}} text-center">{{msg}}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        <div class="expense-form-container">
            <div class="form-header">
                <h5>Input Data Pengeluaran</h5>
                <hr />
            </div>
            <form method="POST" id="expenseForm" data-expense-url="{% url 'dropdown_ajax' %}">
                {% csrf_token %}
                <div class="subtitles">
                    <p class="text-right"><strong><span class="text-rd">*</span> wajib diisi</strong></p>

                    <table class="w-100">
                        <tbody>
                            <tr>
                                <td class="cell-1">
                                    <label for="date_added">Date Added<span class="text-rd">*</span></label>
                                </td>
                                <td>
                                    <div class="width-60">
                                        {{expense_form.date_added}}
                                    </div>
                                </td>
                            </tr>

                            <tr>
                                <td class="cell-1">
                                    <label for="item_name">Item Name: <span class="text-rd">*</span></label>
                                </td>
                                <td>
                                    <div class="width-60">
                                        {{expense_form.item_name}}
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <table class="w-100 table-border-top mt-3">
                        </tbody>
                            <tr class="table-padding-top">
                                <td class="cell-2">
                                    <label for="category">Category: <span class="text-rd">*</span></label>
                                    <div>
                                        {{expense_form.category}}
                                    </div>
                                </td>
                                <td>
                                    <div style="display:none" id="subCategoryHidden" class="table-padding-left">
                                        <label for="sub_category">Sub Category: <span class="text-rd">*</span></label>
                                        <div class="width-55">
                                        {{expense_form.sub_category}}
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <table class="w-100 table-border-bottom table-border-top mt-3 mb-3">
                        <tbody>
                            <tr class="table-padding-bottom table-padding-top">
                                <td class="cell-1">
                                    <label for="quantity">Quantity: <span class="text-rd">*</span></label>
                                    <div class="width-40">
                                        {{expense_form.quantity}}
                                    </div>
                                </td>
                                <td class="table-padding-left">
                                    <label for="price">Price: <span class="text-rd">*</span></label>
                                    <div class="width-60">
                                        {{expense_form.price}}
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <table class="w-100">
                        <tbody>
                            <tr>
                                <td class="cell-1">
                                    <label for="notes">Notes: (optional)</label>
                                </td>
                                <td>
                                    {{expense_form.notes}}
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <h5>Total:</h5>
                                </td>
                                <td>
                                    <h4 id="totalPrice">0</h4>
                                </td>
                            </tr>
                            
                            <tr>
                                <td></td>
                                <td>
                                    <button type="submit" class="btn btn-color-primary float-right">Submit</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content%}

{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function(){
        // Ajax for dependent dropdown of category field and sub category field
        $("#id_category").change(function(){
            var url = $("#expenseForm").attr("data-expense-url");
            var categoryId = $(this).val();
            $.ajax({
                url: url,
                data: {
                    "category": categoryId,
                },
                success: function(data){
                    $("#id_sub_category").html(data);
                }
            });
        });

        // Show sub category field when category field filled
        $("#id_category").change(function(){
            var control = $(this);
            if(control.val()){
                $("#subCategoryHidden").show();
            }
        })
    });
</script>
<script>
    // Auto sum in real time
    $(function(){
        $("#id_quantity, #id_price").change(function(){
            var qty = parseFloat($("#id_quantity").val()) || 0;
            var prc = parseFloat($("#id_price").val()) || 0;

            $("#totalPrice").text(qty*prc);
        });
    });
</script>
{% endblock js %}

books/templates/books/register_income.html
{% extends 'base/base_test.html' %}
<!-- A front end 'total' field will be added via js -->

{% block title %}
Add Income
{% endblock title %}

{% block css %}
<link href="/../../static/books/books.css" rel="stylesheet">
<link href="/../../static/books/register_income.css" rel="stylesheet">
{% endblock css%}

{% block content %}
<div class="page-content">
    <div class="w-100 h-100">
        <div>
            {% if messages %}
                {% for msg in messages %}
                    {% if msg.tags %}
                        <div class="col-8 msg-{{msg.tags}}-container">
                            <p class="msg-{{msg.tags}} text-center">{{msg}}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        <div class="income-form-container">
            <div class="form-header">
                <h5>Input Data Pemasukan</h5>
                <hr />
            </div>
            <form method="POST" id="incomeForm" data-income-url="{% url 'income_form_autofill' %}">
                {% csrf_token %}
                <div class="subtitles">
                    <p class="text-right"><strong><span class="text-rd">*</span> wajib diisi</strong></p>
                    <table>
                        <tbody>
                            <tr class="table-padding-bottom">
                                <td class="cell-1">
                                    <label for="date_added">Date Added: <span class="text-rd">*</span></label>
                                </td>
                                <td>
                                    <div class="width-40">
                                        {{income_form.date_added}}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="cell-1">
                                    <label for="product_name">Product Name: <span class="text-rd">*</span></label>
                                </td>
                                <td>
                                    <div class="width-40">
                                    {{income_form.product_name}}
                                    </div>
                                </td>
                            </tr>

                            <tr><td><br/></td></tr>

                            <tr class="table-padding-top table-border-top">
                                <td class="cell-1">
                                    <label for="quantity">Quantity: <span class="text-rd">*</span></label>
                                    <div class="qty width-60">
                                        {{income_form.quantity}}
                                    </div>
                                </td>
                                <td>
                                    <label for="price">Price: <span class="text-rd">*</span></label>
                                    <div class="width-50">
                                        {{income_form.price}}
                                    </div>
                                </td>
                            </tr>
                            <tr class="table-padding-bottom table-border-bottom">
                                <td></td>
                                <td>
                                    <label for="additional_price">Additional Price: (optional)</label>
                                    <div class="width-50">
                                        {{income_form.additional_price}}
                                    </div>
                                </td>
                            </tr>

                            <tr><td><br/></td></tr>

                            <tr class="table-padding-bottom">
                                <td class="cell-1">
                                    <label for="notes">Notes: (optional)</label>
                                </td>
                                <td>
                                    <div style="max-height: 50%">
                                        {{income_form.notes}}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="cell-1">
                                    <h5 class="subtitles">Total:</h5>
                                </td>
                                <td>
                                    <h4 id="totalPrice" class="subtitles">0</h4>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="float-right">
                                    <button type="submit" class="btn btn-color-primary mt-2">Submit</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function(){
        $("#id_product_name").change(function(){
            var url = $("#incomeForm").attr("data-income-url");
            var prcId = $(this).val()
            $.ajax({
                url: url,
                data: {
                    "product_name": prcId,
                },
                success: function(data){
                    // You need parseFloat so the form field could detect it as float type, or parseInt for integer type
                    // This is applied only if your form field required a number input, refer to expense page for string type
                    var prc = parseFloat(data);
                    $("#id_price").val(prc)
                }
            })
        })
    });
</script>
<script>
    $(function(){
        $("#id_quantity, #id_price, #id_additional_price").change(function(){
            var qty = parseFloat($("#id_quantity").val()) || 0;
            var prc = parseFloat($("#id_price").val()) || 0;
            var add_prc = parseFloat($("#id_additional_price").val()) || 0;

            $("#totalPrice").text((qty*prc)+add_prc);
        });
    });
</script>
{% endblock js %}

books/templates/books/register_product.html
{% extends 'base/base_test.html' %}

{% block title %}
Register Product
{% endblock title %}

{% block css %}
<link href="/../../static/books/register_product.css" rel="stylesheet">
<link href="/../../static/books/books.css" rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="page-content">
    <div class="h-100 w-100">
        <div>
            {% if messages %}
                {% for msg in messages %}
                    {% if msg.tags %}
                        <div class="col-8 msg-{{msg.tags}}-container">
                            <p class="msg-{{msg.tags}} text-center">{{msg}}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        <div class="product-form-container">
            <div class="form-header">
                <h5>Input Produk</h5>
                <hr />
            </div>

            <form method="POST">
                {% csrf_token %}
                <p class="subtitles text-right"><strong><span class="text-rd">*</span> wajib diisi</strong></p>
                <div class="mb-2">
                    <label for="product_name" class="subtitles">Product Name: <span class="text-rd">*</span></label>
                    {{product_form.product_name}}
                </div>

                <label for="price" class="subtitles">Price: <span class="text-rd">*</span></label>
                {{product_form.price}}

                <label for="type" class="subtitles mt-2">Type:<span class="text-rd">*</span></label>
                {{product_form.types}}

                <button type="submit" class="btn btn-color-primary btn-sm float-right mt-2">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}